name: Console Log

on:
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - "**"

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: echo "Hello, this is a console log message!"
